version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./conf:/etc/prometheus
      - ./data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    restart: on-failure

  grafana:
    image: grafana:6.3.3
    build:
      context: ./Grafana/
      dockerfile: Dockerfile
    container_name: grafana-v.6.3.3
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - prometheus
